params:
  models:
    - 'LinearRegression'
    - 'RandomForestRegressor'
  expression_scales:
    - 'linear'
  complex_expression_aggregation:
    - 'product' # mass action kinetics
  interaction_expression_aggregation:
    - 'product' # mass action kinetics
  interaction_sources:
    - 'CellPhoneDB'
  
  