params:
  models:
    - 'LinearRegression'
    - 'RandomForestRegressor'
  expression_scales:
    - 'linear'
    - 'log'
    #- 'binary'
  complex_expression_aggregation:
    - 'min'
    - 'mean' # todo
    - 'sum' # todo
  interaction_sources:
    - 'CellPhoneDB'
  interaction_models:
    - 'basic'
  
  