name: lr-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - pandas
  - numpy
  - scipy
  - anndata
  - scanpy
  - snakemake>=6.0
  - altair
  - jupyterlab
  - pip
  - pip:
    - daft