name: lr-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - pandas
  - numpy
  - scipy
  - anndata
  - scanpy
  - snakemake>=6.0
  - altair
  - jupyterlab
  - networkx
  - zarr
  - numcodecs
  - xlrd
  - openpyxl
  - pip
  - pip:
    - daft
    - biomart
    - obonet
    - cmapPy