name: lr-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - snakemake>=6.0
  - pandas
  - numpy
  - scipy
  - anndata
  - scanpy
  - altair
  - altair_saver
  - jupyterlab
  - networkx
  - zarr
  - numcodecs
  - xlrd
  - openpyxl
  - scikit-learn
  - lxml
  - cssselect
  - requests
  - adjusttext
  - biopython
  - pip
  - pip:
    - daft
    - biomart
    - obonet
    - cmapPy
    - UpSetPlot
    - pyensembl